set(ENGINE_HEADER_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/include/engine/window.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/engine/input.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/engine/shader.hpp
)
set(ENGINE_SRC_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/engine/window.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/engine/shader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/engine/deps.cpp
)